name: build and push and deploy

on:
  push:
    branches:
      - env-test


permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'


      - name: uruchom srodowisko docker-compose
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yml --env-file .env -p local-prge up --build -d

