name: build and push and deploy

on:
  push:
    branches:
      - env-test


permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'


      - name: uruchom srodowisko docker-compose
        env:
          #DB
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yml -p remote-prge up --build -d

